# Generated by Django 2.1.2 on 2018-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название категории')),
                ('info', models.TextField(verbose_name='Описание категории')),
                ('price', models.PositiveIntegerField(verbose_name='Цена от')),
                ('img', models.ImageField(upload_to='categories/%Y/%m/%d', verbose_name='Картинка категории')),
            ],
        ),
    ]
