# Generated by Django 2.1.3 on 2018-12-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Категория')),
                ('info', models.TextField(verbose_name='Описание категории')),
                ('price', models.PositiveIntegerField(verbose_name='Цена от')),
                ('img', models.ImageField(upload_to='categories/%Y/%m/%d', verbose_name='Картинка категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название проекта')),
                ('info', models.TextField(verbose_name='Описание проекта')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Картинка проекта')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Category')),
            ],
        ),
    ]
