# Generated by Django 2.1.2 on 2018-12-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181201_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Название проекта')),
                ('info', models.TextField(verbose_name='Описание проекта')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Картинка проекта')),
                ('category', models.ForeignKey(null=True, on_delete=models.SET('NULL'), to='mainapp.Category')),
            ],
        ),
    ]
